"""your_migration_message

Revision ID: 3f3c543cf7b8
Revises: 6a350c92c150
Create Date: 2025-08-18 20:14:13.264670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f3c543cf7b8'
down_revision: Union[str, None] = '6a350c92c150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'onboarding_completed')
    # ### end Alembic commands ###
