"""add users table

Revision ID: 513b2a642433
Revises: aa9c0c5cfd30
Create Date: 2025-08-18 21:55:03.291826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513b2a642433'
down_revision: Union[str, None] = 'aa9c0c5cfd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'provider')
    # ### end Alembic commands ###
