"""add provider column to users

Revision ID: 9add00f9a875
Revises: e66043fbd13c
Create Date: 2025-08-18 22:14:08.273879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9add00f9a875'
down_revision: Union[str, None] = 'e66043fbd13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('provider', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'provider')
    # ### end Alembic commands ###
