"""your_migration_message

Revision ID: aa9c0c5cfd30
Revises: 3f3c543cf7b8
Create Date: 2025-08-18 20:15:08.427294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9c0c5cfd30'
down_revision: Union[str, None] = '3f3c543cf7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
