"""add provider column to users

Revision ID: e66043fbd13c
Revises: 513b2a642433
Create Date: 2025-08-18 22:12:01.596488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66043fbd13c'
down_revision: Union[str, None] = '513b2a642433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('provider', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'provider')
    # ### end Alembic commands ###
