"""add lname column to user

Revision ID: ffde95e9f9d2
Revises: 45f7c66353f4
Create Date: 2025-08-15 18:07:48.735629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffde95e9f9d2'
down_revision: Union[str, None] = '45f7c66353f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lname', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lname')
    # ### end Alembic commands ###
